[package]
name = "polycarp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1"
fn-error-context = "0.2"
heck = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
utils = { path = "../utils" }
